# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nl2sql.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nl2sql.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cnl2sql.proto\"1\n\rNL2SQLRequest\x12\x10\n\x08nl_query\x18\x01 \x01(\t\x12\x0e\n\x06schema\x18\x02 \x01(\t\"\x1d\n\x0eNL2SQLResponse\x12\x0b\n\x03sql\x18\x01 \x01(\t2;\n\x0bNL2SQLAgent\x12,\n\tTranslate\x12\x0e.NL2SQLRequest\x1a\x0f.NL2SQLResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nl2sql_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NL2SQLREQUEST']._serialized_start=16
  _globals['_NL2SQLREQUEST']._serialized_end=65
  _globals['_NL2SQLRESPONSE']._serialized_start=67
  _globals['_NL2SQLRESPONSE']._serialized_end=96
  _globals['_NL2SQLAGENT']._serialized_start=98
  _globals['_NL2SQLAGENT']._serialized_end=157
# @@protoc_insertion_point(module_scope)
